version: '3'

services:
  mongodb:
    image: 'mongo:latest'
    container_name: 'mongodb'
    volumes:
      - ${PWD}/db:/data/db
    ports:
      - '27017:27017'
    expose:
      - 27017
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - 'discovery.type=single-node'
    restart: always
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
      - 'eslogs:/usr/share/elasticsearch/logs'

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.14.0
    volumes:
      - 'fblogs:/var/log/:ro'
      - 'fbdata:/var/run/docker.sock'
      - 'applogs:/var/lib/docker/containers/logs:ro'
      - './filebeat.yml:/usr/share/filebeat/filebeat.yml'
    restart: always
    command: ['--strict.perms=false']
    depends_on:
      - 'elasticsearch'

  kibana:
    image: docker.elastic.co/kibana/kibana:7.14.0
    ports:
      - 5601:5601
    restart: always
    depends_on:
      - 'elasticsearch'
      - 'filebeat'

  backend:
    image: 'y0rch/devs-social-backend:latest'
    container_name: 'backend'
    ports:
      - '${PORT}:${PORT}'
    expose:
      - ${PORT}
    restart: always
    environment:
      - PORT
      - MONGO_URI
      - JWT_SECRET_KEY
    volumes:
      - 'applogs:/logs'
    depends_on:
      - mongodb
      - filebeat

volumes:
  esdata:
    driver: local
  eslogs:
    driver: local
  fblogs:
    driver: local
  fbdata:
    driver: local
  applogs:
    driver: local
