# This workflow will run the project tests
name: CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'src/**/*'
      - 'Dockerfile'
  pull_request:
    branches: [main]
    paths:
      - 'src/**/*'

jobs:
  ci:
    runs-on: ubuntu-latest
    container:
      image: node

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        mongodb-version: ['4.0', '4.2', '4.4']

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.6.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - run: npm ci

      - name: Run tests
        env:
          PORT: 5000
          MONGO_URI: 'mongodb://localhost:27017/app'
          MONGO_URI_TEST: 'mongodb://localhost:27017/test'
          JWT_SECRET_KEY: JWT_TEST_KEY
        run: npm test token && npm test user && npm test post

  cd:
    name: Buils Docker image and push to Docker Hub
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t backend .
      - name: Tags
        run:  |
          docker tag backend ${{ secrets.DOCKER_USER }}/devs-social-backend:${{ github.sha }}
          docker tag backend ${{ secrets.DOCKER_USER }}/devs-social-backend:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/devs-social-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/devs-social-backend:latest
