name: Publish Docker image

on:
  push:
    branches: [main]
    paths:
      - 'src/'
      - 'Dockerfile'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t backend .
      - name: Tags
        run:  |
          docker tag backend ${{ secrets.DOCKER_USER }}/devs-social-backend:${{ github.sha }}
          docker tag backend ${{ secrets.DOCKER_USER }}/devs-social-backend:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/devs-social-backend:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/devs-social-backend:latest   